In [2]:
!python3 -m pip install numpy

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.dtype)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
int64


In [12]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1 = arr1.reshape(1,5)
print(arr1)

arr1 = arr1.reshape(5,1)
print(arr1)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
## 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [18]:
## create array with inbuilt function
arr3 = np.arange(1, 10, 2).reshape(5, 1)
print(arr3)
print(arr3.shape)
print(arr3.dtype)


[[1]
 [3]
 [5]
 [7]
 [9]]
(5, 1)
int64


In [19]:
np.ones((2, 3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)
print("Size:", arr.size)
print("Item size (bytes):", arr.itemsize)
print("Total bytes consumed:", arr.nbytes)
print("Array data (flattened):", arr.flatten())
print("Array data (transposed):", arr.T)
print("Array data (sliced):", arr[0, 1:3])

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data type: int64
Number of dimensions: 2
Size: 6
Item size (bytes): 8
Total bytes consumed: 48
Array data (flattened): [1 2 3 4 5 6]
Array data (transposed): [[1 4]
 [2 5]
 [3 6]]
Array data (sliced): [2 3]


In [24]:
## mathemetical operation
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print("Addition:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Element-wise Multiplication:\n", arr1 * arr2)
print("Element-wise Division:\n", arr1 / arr2)
print("Matrix Multiplication:\n", np.dot(arr1, arr2.T))


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
Matrix Multiplication:
 [[ 50  68]
 [122 167]]


In [25]:
## universal function
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Square root:\n", np.sqrt(arr1))
print("Exponential:\n", np.exp(arr1))
print("Logarithm:\n", np.log(arr1))
print("Sine:\n", np.sin(arr1))
print("Cosine:\n", np.cos(arr1))


Square root:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Exponential:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
Logarithm:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
Sine:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
Cosine:
 [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [27]:
## slicing and squaring
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:\n", arr)
print("Sliced Array (first row):\n", arr[0])
print("Sliced Array (second column):\n", arr[:, 1])
print("Squared Array:\n", arr ** 2)
print(arr[0:, 1:3])


Original Array:
 [[1 2 3]
 [4 5 6]]
Sliced Array (first row):
 [1 2 3]
Sliced Array (second column):
 [2 5]
Squared Array:
 [[ 1  4  9]
 [16 25 36]]
[[2 3]
 [5 6]]


In [29]:
## statical concept - normalization
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(arr)
std = np.std(arr)

## normalization
normalized = (arr - mean) / std
print("Normalized Array:\n", normalized)


Normalized Array:
 [[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


In [31]:
## mean, median, mode, variance, standard deviation
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)


print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Mean: 3.5
Median: 3.5
Variance: 2.9166666666666665
Standard Deviation: 1.707825127659933


In [32]:
## logical operation
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])
print("Logical AND:\n", np.logical_and(arr1 > 2, arr2 < 5))
print("Logical OR:\n", np.logical_or(arr1 > 2, arr2 < 5))
print("Logical NOT:\n", np.logical_not(arr1 > 2))


Logical AND:
 [[False False  True]
 [ True  True  True]]
Logical OR:
 [[False False  True]
 [ True  True  True]]
Logical NOT:
 [[ True  True False]
 [False False False]]
